Update docker-image-arm64.yml

diff --git a/.github/workflows/docker-image-arm64.yml b/.github/workflows/docker-image-arm64.yml
--- a/.github/workflows/docker-image-arm64.yml
+++ b/.github/workflows/docker-image-arm64.yml
@@ -13,14 +13,21 @@ jobs:
         
       - name: Build and push ARM64 Docker image
         run: |
-          wget https://desktop.docker.com/mac/main/arm64/137060/Docker.dmg
-          sudo hdiutil attach Docker.dmg
-          sudo /Volumes/Docker/Docker.app/Contents/MacOS/install  --accept-license --user='runner'
-          sudo hdiutil detach /Volumes/Docker
-          export PATH=$PATH:~/.docker/bin
-          sudo xattr -r -d com.apple.quarantine /Applications/Docker.app
-          brew install colima
-          colima start
+          # wget https://desktop.docker.com/mac/main/arm64/137060/Docker.dmg
+          # sudo hdiutil attach Docker.dmg
+          # sudo /Volumes/Docker/Docker.app/Contents/MacOS/install  --accept-license --user='runner'
+          # sudo hdiutil detach /Volumes/Docker
+          # export PATH=$PATH:~/.docker/bin
+          # sudo xattr -r -d com.apple.quarantine /Applications/Docker.app
+
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+
+
+          
           until sudo docker login -u akhilrana -p ${{ secrets.DOCKER_PASSWORD }}; do sleep 1; done
           until sudo docker build -t akhilrana/telegramarr:latest-arm64 .; do sleep 1; done
           sudo docker push akhilrana/telegramarr:latest-arm-64
